// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package simple_bank

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   pgtype.Numeric
	Currency  string
	CreatedAt pgtype.Timestamptz
}

type Entry struct {
	ID        int64
	AccountID int64
	// can be negative or positive
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// must be positive
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}
